### ISSUE TITLE
Isoplot concordia difference

### ISSUE THREAD

**Issue by zensfate** [CIRDLES/Topsoil#120] opened 2015-05-07 22:24 UTC
1. When compared with Isoplot, the error ellipses from Topsoil are ~20% smaller, even though the ratios, uncertainties, and error correlations are exactly the same. My guess is that this is due to assumptions about the uncertainty level on input. In Isoplot, we specify that the uncertainty level on input is 1-sigma, and then output ellipses at 2-sigma. In Topsoil there is no way to specify the uncertainty level on input -- is it assumed to be 2-sigma? Can't imagine why this would create a ~20% difference (should be 2x), but can't think of any other reason why the output would be different!
2. We've noticed that the difference between 2-sigma and 95-level output is very similar for Isoplot, but significantly greater for Topsoil. Again for the same data on input. Any idea why this is the case?
3. We also notice that ellipses are offset slightly to the left (relative to concordia) on Topsoil relative to Isoplot. Is this because Isoplot is currently set to 137.88, whereas Topsoil uses 137.82? If not, I can't imagine why there would be a systematic shift!?

With these issues is there a way to expose the assumptions topsoil is making to get the same results as isoplot? Or could someone point out the space in the code that makes the assumptions so that we could try some changes.

**Comment by johnzeringue** [comment] 2015-05-08 03:48
Hi @zensfate. I appreciate you reporting these issues. If you wouldn't mind, I could use a little more help from you.

First, which version of Topsoil are you using? The latest release is [`v0.4.2`](https://github.com/CIRDLES/Topsoil/releases/tag/v0.4.2).

Second, it's difficult to troubleshoot sizing discrepancies without screenshots and steps to reproduce. If you could provide these, it would be tremendously helpful.

Third, you say that

> In Topsoil there is no way to specify the uncertainty level on input -- is it assumed to be 2-sigma?

This is incorrect. In `v0.4.2`, after pressing "Uncertainty ellipse chart", you are able to specify both the uncertainty and the expression format (percent or absolute) using the drop down boxes in the new window that appears.

If you're concerned about our process for generating the ellipses, the logic for generating the Bezier control points can be found [here](https://github.com/CIRDLES/Topsoil/blob/305ca5d54684edf75c3f4e47c66ffb2ef32d882e/src/main/java/org/cirdles/topsoil/chart/concordia/ErrorEllipse.java) between lines 105 and 129. The values for `confidenceLevel` are specified [here](https://github.com/CIRDLES/Topsoil/blob/305ca5d54684edf75c3f4e47c66ffb2ef32d882e/src/main/java/org/cirdles/topsoil/chart/concordia/ErrorChartToolBar.java) and are 1, 2, and 2.4477, corresponding with the confidence levels 1σ, 2σ, and 95%. Topsoil currently uses 137.88 as seen [here](https://github.com/CIRDLES/Topsoil/blob/305ca5d54684edf75c3f4e47c66ffb2ef32d882e/src/main/java/org/cirdles/math/Constant.java).

Again, it's difficult for me to troubleshoot these issues without screenshots, steps, and possibly SVGs demonstrating any perceived issues.

Unfortunately, I'm not entirely knowledgable about the process Isoplot uses to generate its SVGs, so I can't say for certain whether or not our plots _should_ look identical, even when using the same constants. Perhaps @noahmclean can shed some light on this.

Finally, thanks for trying Topsoil. Hopefully, we'll be able to fully address your concerns.

**Comment by bowring** [comment] 2015-05-13 18:47
Hi @zensfate - We want to solve this for you, so if you can supply the data table, we can compare Topsoil and Redux, but we need an output from Isoplot to compare with.

**Comment by zensfate** [comment] 2015-05-16 15:29
Let me build some data comparisons for you with some screenshots. I have ot had time this last week but should have time next week.

Isaac

**Comment by bowring** [comment] 2015-05-17 13:07
great!

On Sat, May 16, 2015 at 11:29 AM, zensfate <notifications@github.com> wrote:

> Let me build some data comparisons for you with some screenshots. I have
> ot had time this last week but should have time next week.
>
> Isaac
>
>
>
> > On May 7, 2015, at 8:48 PM, John Zeringue <notifications@github.com>
> wrote:
> >
> > Hi @zensfate. I appreciate you reporting these issues. If you wouldn't
> mind, I could use a little more help from you.
> >
> > First, which version of Topsoil are you using? The latest release is
> v0.4.2.
> >
> > Second, it's difficult to troubleshoot sizing discrepancies without
> screenshots and steps to reproduce. If you could provide these, it would be
> tremendously helpful.
> >
> > Third, you say that
> >
> > In Topsoil there is no way to specify the uncertainty level on input --
> is it assumed to be 2-sigma?
> >
> > This is incorrect. In v0.4.2, after pressing "Uncertainty ellipse
> chart", you are able to specify both the uncertainty and the expression
> format (percent or absolute) using the drop down boxes in the new window
> that appears.
> >
> > If you're concerned about our process for generating the ellipses, the
> logic for generating the Bezier control points can be found here between
> lines 105 and 129. The values for confidenceLevel are specified here and
> are 1, 2, and 2.4477, corresponding with the confidence levels 1σ, 2σ, and
> 95%. Topsoil currently uses 137.88 as seen here.
> >
> > Again, it's difficult for me to troubleshoot these issues without
> screenshots, steps, and possibly SVGs demonstrating any perceived issues.
> >
> > Unfortunately, I'm not entirely knowledgable about the process Isoplot
> uses to generate its SVGs, so I can't say for certain whether or not our
> plots should look identical, even when using the same constants. Perhaps
> @noahmclean can shed some light on this.
> >
> > Finally, thanks for trying Topsoil. Hopefully, we'll be able to fully
> address your concerns.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/issues/120#issuecomment-102638693>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org <http://www.CIRDLES.org%20>

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by zensfate** [comment] 2015-05-18 23:03
So my quick isoplot screen shot is in the attachment. I will try to get
something a little cleaner from a larger dataset. this one  is from a short
5 point set of data.

**Comment by johnzeringue** [comment] 2015-05-19 02:45
Attachments don't come through. You need to use the issue tracker on the website. Instructions for adding images are at the bottom of the text box.

**Comment by zensfate** [comment] 2015-05-20 00:00
Using Windows 7 with jre-8u40-windows-x64 and topsoil-v0.4.2.jar

Using a set of standard data in topsoil
7/5 ratio	±(%)	6/8 ratio	±(%)	errcorr
0.73323	1.8	0.09082	0.8	0.43
0.74074	1.6	0.09102	0.9	0.56
0.73945	2.0	0.09114	1.1	0.55
0.73293	1.6	0.09095	1.0	0.64
0.73854	2.8	0.09094	1.2	0.45

This generates the following graph
![image](https://cloud.githubusercontent.com/assets/1907607/7716513/d955ec3a-fe47-11e4-8475-b75f39f39cbd.png)
 

The same data set in Microsoft Excell and isoplot 4.15
 
 
![image](https://cloud.githubusercontent.com/assets/1907607/7716497/bc8bc796-fe47-11e4-8397-96c88dee50cb.png)

![image](https://cloud.githubusercontent.com/assets/1907607/7716490/9bb80868-fe47-11e4-9d89-acc7703397e1.png)


It is an odd difference that I can not quite identify.

**Comment by johnzeringue** [comment] 2015-05-20 02:37
The chart below should copy/paste easier.

7/5 ratio | ±(%) | 6/8 ratio | ±(%) | errcorr
----------|------|-----------|------|--------
0.73323 | 1.8 | 0.09082 | 0.8 | 0.43
0.74074 | 1.6 | 0.09102 | 0.9 | 0.56
0.73945 | 2.0 | 0.09114 | 1.1 | 0.55
0.73293 | 1.6 | 0.09095 | 1.0 | 0.64
0.73854 | 2.8 | 0.09094 | 1.2 | 0.45

---

Thanks for the screenshots. I can certainly see differences. To name a couple:

- There's overlap at the top of the Topsoil output that doesn't exist in the Isoplot output.
- The Topsoil output appears to be smaller than the Isoplot output with respect the x-axis, the y-axis, and the concordia line.

@bowring and I will plot this dataset in ET_Redux and report back, and then we can go from there.

**Comment by noahmclean** [comment] 2015-05-25 03:49
Hi all, I think there's a pretty straightforward explanation here.  Happily, everyone is correct.  

Univariate confidence intervals (e.g. x ± y) are often reported at the 1σ or 2σ levels, which for normal distributions have a ~68% and ~95% probability of containing the true value of the measured variable.  Bivariate uncertainty envelopes, aka 'error ellipses', have 1σ and 2σ sizes as well.  What's important here is that these have different confidence levels: a 1σ ellipse has a 39.3% probability of containing the true value, and a 2σ ellipse has an 86.5% probability of the same.   How to calculate, plot, and interpret these confidence intervals will be the subject of a help document in Topsoil.

It looks like what Isoplot is doing, according to the text at the top right of the plot, is plotting ellipses with the same 68.3% confidence level as a univariate 1σ confidence interval.  For bivariate (2D) ellipses, that's the same as a 1.52σ ellipse.  That explains why the Isoplot ellipses are larger than the Topsoil 1σ ones... and smaller than the 2σ ellipses.  

@zensfate, if you want to check what each program is doing, enter some test data: x- and y-values of zero, 1σ absolute uncertainties of 1, and a correlation coefficient of zero.  This should plot a circle at the origin.  A 1σ ellipse (here, circle) will have a radius of 1, a 2σ ellipse will have a radius of 2, and a 68.3% confidence interval should have a radius of 1.52.

**Comment by johnzeringue** [comment] 2015-05-26 06:12
@noahmclean, thanks for the info! That certainly helps me.

@zensfate, if @noahmclean's addressed your concerns, please close this issue. Otherwise, feel free to reply again with questions about things you're still uncertain about.

**Closed** 2015-09-24 22:14 UTC
Labels: question
